apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: edmp
data:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://REPLACE_RDS_ENDPOINT/sonar"
  SONARQUBE_JDBC_USERNAME: "sonar"
---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-secret
  namespace: edmp
type: Opaque
data:
  SONARQUBE_JDBC_PASSWORD: c29uYXIxMjMh  # base64 encoded "sonar123!"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: edmp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: edmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.9.2-community
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: sonar-config
              key: SONARQUBE_JDBC_URL
        - name: SONARQUBE_JDBC_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sonar-config
              key: SONARQUBE_JDBC_USERNAME
        - name: SONARQUBE_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonar-secret
              key: SONARQUBE_JDBC_PASSWORD
        volumeMounts:
        - name: sonar-data
          mountPath: /opt/sonarqube/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 180
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: edmp
spec:
  selector:
    app: sonarqube
  ports:
  - port: 9000
    targetPort: 9000
  type: LoadBalancer